# Generated by Django 6.0.4 on 2026-04-28 14:52

from decimal import Decimal

from django.db import migrations, models


def seed_payment_method_adjustments(apps, schema_editor):
    PaymentMethodAdjustment = apps.get_model('payments', 'PaymentMethodAdjustment')
    defaults = {
        'online_card': Decimal('0.00'),
        'cash_on_delivery': Decimal('-10.00'),
        'card_on_delivery': Decimal('10.00'),
    }
    for payment_method, adjustment_percent in defaults.items():
        PaymentMethodAdjustment.objects.update_or_create(
            payment_method=payment_method,
            defaults={
                'adjustment_percent': adjustment_percent,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethodAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("online_card", "Online Card"),
                            ("cash_on_delivery", "Cash on Delivery"),
                            ("card_on_delivery", "Card on Delivery"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "adjustment_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["payment_method"],
            },
        ),
        migrations.RunPython(seed_payment_method_adjustments, migrations.RunPython.noop),
    ]
