# Generated by Django 5.2.13 on 2026-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_bookings_bo_user_id_5943d6_idx_and_more'),
        ('payments', '0003_payment_payments_pa_status_7ad4af_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='payments_pa_provide_3e1786_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['provider', 'event_id'], name='payments_pa_provide_1feafd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['processed', 'processed_at'], name='payments_pa_process_d8d27e_idx'),
        ),
    ]
