# Generated by Django 5.2.13 on 2026-04-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polygon_json', models.JSONField(blank=True, null=True)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('free_delivery', models.BooleanField(default=False)),
                ('base_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
