# Generated by Django 5.2.13 on 2026-04-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='radius_km',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
