# Generated by Django 6.0.4 on 2026-04-28 14:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_deliveryzone_created_at_deliveryzone_radius_km_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="deliveryaddress",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="deliveryzone",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="polygon",
            field=models.JSONField(
                blank=True,
                help_text='List of points: [{"lat": ..., "lng": ...}, ...]',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="base_price_usd",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="center_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="center_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="price_per_km_usd",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.CreateModel(
            name="DeliveryPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="delivery.deliveryzone",
                    ),
                ),
            ],
            options={
                "ordering": ["zone__name", "-is_active", "-created_at"],
            },
        ),
    ]
