# Generated by Django 4.2.30 on 2026-04-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverypoint_alter_deliveryaddress_options_and_more'),
        ('pricing', '0004_cleanup_orphaned_price_log_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryzone',
            name='free_delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='polygon_json',
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='is_free',
            field=models.BooleanField(db_column='free_delivery', default=False),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='polygon',
            field=models.JSONField(blank=True, db_column='polygon_json', help_text='List of points: [{"lat": ..., "lng": ...}, ...]', null=True),
        ),
    ]
