# Generated by Django 5.2.13 on 2026-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_deliveryzone_free_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='center_lat',
            field=models.FloatField(blank=True, help_text='DEPRECATED: Use polygon instead.', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='center_lng',
            field=models.FloatField(blank=True, help_text='DEPRECATED: Use polygon instead.', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='is_free',
            field=models.BooleanField(db_column='free_delivery', default=False, help_text='Use this flag for flat free-delivery zones.'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='polygon',
            field=models.JSONField(blank=True, db_column='polygon_json', help_text='List of points: [{"lat": ..., "lng": ...}, ...]', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='radius_km',
            field=models.FloatField(default=5.0, help_text='DEPRECATED: Use polygon instead.'),
        ),
    ]
