# Generated by Django 5.2.13 on 2026-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverypoint_alter_deliveryaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='center_lat',
            field=models.FloatField(blank=True, help_text='DEPRECATED: Use polygon instead.', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='center_lng',
            field=models.FloatField(blank=True, help_text='DEPRECATED: Use polygon instead.', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='free_delivery',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use is_free instead.'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='polygon_json',
            field=models.JSONField(blank=True, help_text='DEPRECATED: Use polygon instead.', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='radius_km',
            field=models.FloatField(default=5.0, help_text='DEPRECATED: Use polygon instead.'),
        ),
    ]
