# Generated by Django 4.2.30 on 2026-05-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliveryzone_center_lat_and_more'),
        ('delivery', '0005_remove_deliveryzone_free_delivery_and_more'),
    ]

    operations = [
    ]
