# Generated by Django 5.2.13 on 2026-04-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
