# Generated by Django 6.0.4 on 2026-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userdevice_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("staff", "Staff"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
