server {
    listen 80;
    server_name bali.bike api.bali.bike;

    client_max_body_size 50M;

    location /static/ {
        alias /var/www/bali_rent/static/;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /var/www/bali_rent/media/;
        expires 1d;
        add_header Cache-Control "public";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/bali_rent/gunicorn.sock;
        proxy_redirect off;
        proxy_read_timeout 120s;
    }
}
