# Generated by Django 5.2.14 on 2026-05-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Dot path, e.g. nav.catalog or media.home.heroVideo', max_length=255)),
                ('language', models.CharField(choices=[('all', 'All languages'), ('en', 'English'), ('ru', 'Русский'), ('zh', '中文'), ('id', 'Indonesia'), ('de', 'Deutsch'), ('fr', 'Français')], default='en', max_length=10)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('json', 'JSON'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='text', max_length=20)),
                ('value', models.TextField(blank=True, default='', help_text='Text value or external media URL fallback.')),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='site_content/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site content entry',
                'verbose_name_plural': 'Site content entries',
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
