# Generated by Django 5.2.13 on 2026-04-28 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analyticsevent',
            name='analytics_a_user_id_864607_idx',
        ),
        migrations.RenameField(
            model_name='analyticsevent',
            old_name='properties',
            new_name='payload',
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_ecb128_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id', 'created_at'], name='analytics_a_session_533ea7_idx'),
        ),
    ]
