# Generated by Django 6.0.4 on 2026-04-28 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_vehicle_options"),
        ("pricing", "0002_refactor_dynamic_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="season",
            new_name="pricing_sea_code_77a776_idx",
            old_name="pricing_sea_code_16da58_idx",
        ),
        migrations.AlterField(
            model_name="devicepricingrule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="geopricingrule",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="geopricingrule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="occupancypricingrule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pricecalculationlog",
            name="payload_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="pricecalculationlog",
            name="scooter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_logs",
                to="catalog.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="pricecalculationlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
