# Generated by Django 5.2.15 on 2026-06-21 16:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_scooterrentalrate_and_migrate_vehicle_prices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scooterrentalrate',
            new_name='pricing_sco_scooter_0b5113_idx',
            old_name='pricing_sco_scooter_b26abf_idx',
        ),
        migrations.RenameIndex(
            model_name='scooterrentalrate',
            new_name='pricing_sco_scooter_cc8158_idx',
            old_name='pricing_sco_scooter_9576bf_idx',
        ),
        migrations.AlterField(
            model_name='scooterrentalrate',
            name='price_usd',
            field=models.DecimalField(decimal_places=4, help_text='Price charged for each billing period.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
