# Generated by Django 5.2.15 on 2026-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_rename_pricing_sco_scooter_b26abf_idx_pricing_sco_scooter_0b5113_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooterrentalrate',
            name='price_idr',
            field=models.PositiveBigIntegerField(blank=True, help_text='Exact IDR amount entered by the admin. price_usd is derived from this and never used to recompute it, so the rupiah figure never drifts after saving.', null=True),
        ),
    ]
