from copy import deepcopy


PUBLIC_LANGUAGES = [
    {"code": "EN", "api_code": "en", "label": "English", "flag": "🇬🇧"},
    {"code": "RU", "api_code": "ru", "label": "Русский", "flag": "🇷🇺"},
    {"code": "ZH", "api_code": "zh", "label": "中文", "flag": "🇨🇳"},
    {"code": "ID", "api_code": "id", "label": "Indonesia", "flag": "🇮🇩"},
    {"code": "DE", "api_code": "de", "label": "Deutsch", "flag": "🇩🇪"},
    {"code": "FR", "api_code": "fr", "label": "Français", "flag": "🇫🇷"},
]


LANGUAGE_MAP = {item["api_code"]: item for item in PUBLIC_LANGUAGES}


def normalize_public_language(value):
    if not value:
        return "en"

    cleaned = str(value).strip().lower().replace("_", "-")
    short = cleaned.split("-")[0]
    if short in LANGUAGE_MAP:
        return short
    return "en"


def deep_merge(base, override):
    if not isinstance(base, dict) or not isinstance(override, dict):
        return deepcopy(override)

    result = deepcopy(base)
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = deepcopy(value)
    return result


SITE_CONTENT_EN = {
    "common": {
        "loading": "Loading live data...",
        "retry": "Retry",
        "back": "Back",
        "continue": "Continue",
        "save": "Save",
        "cancel": "Cancel",
        "signOut": "Sign Out",
        "free": "Free",
        "included": "Included",
        "secure": "Secure",
        "perDay": "per day",
        "days": "days",
        "day": "day",
        "vehiclePhoto": "vehicle photo",
        "unknownError": "Something went wrong while loading the latest data.",
        "availability": {
            "available": "Available",
            "booked": "Booked",
        },
        "types": {
            "all": "All Types",
            "scooter": "Scooter",
            "maxi": "Maxi Scooter",
            "moto": "Motorcycle",
        },
        "sort": {
            "popular": "Most Popular",
            "price_asc": "Price: Low → High",
            "price_desc": "Price: High → Low",
            "rating": "Highest Rated",
        },
        "paymentMethods": {
            "online_card": "Card Online",
            "cash_on_delivery": "Cash on Delivery",
            "card_on_delivery": "Card on Delivery",
        },
        "documentTypes": {
            "passport": "Passport",
            "driver_license": "Driver's License",
            "selfie": "Selfie with Document",
        },
        "bookingStatuses": {
            "created": "Created",
            "pending_payment": "Pending Payment",
            "paid": "Paid",
            "confirmed": "Confirmed",
            "delivery": "On Delivery",
            "active": "Active",
            "completed": "Completed",
            "cancelled": "Cancelled",
        },
        "documentStatuses": {
            "not_uploaded": "Not uploaded",
            "pending": "Pending review",
            "approved": "Approved",
            "rejected": "Rejected",
        },
        "specLabels": {
            "engine": "Engine",
            "transmission": "Transmission",
            "fuel_consumption": "Fuel Consumption",
            "year": "Year",
            "trunk": "Storage",
            "helmets_count": "Helmets",
            "color": "Color",
        },
    },
    "nav": {
        "fleet": "Fleet",
        "howItWorks": "How It Works",
        "locations": "Locations",
        "faq": "FAQ",
        "signIn": "Sign In",
        "account": "Account",
        "bookNow": "Book Now",
    },
    "footer": {
        "description": "Premium scooter rental in Bali. Delivered to your door, fueled and ready to ride.",
        "columns": [
            {
                "title": "Fleet",
                "links": ["Scooters", "Maxi Scooters", "Motorcycles", "All Vehicles"],
            },
            {
                "title": "Company",
                "links": ["About Us", "How It Works", "Locations", "Support"],
            },
            {
                "title": "Support",
                "links": ["WhatsApp Chat", "FAQ", "Terms & Conditions", "Privacy Policy"],
            },
        ],
        "bottomLinks": ["Fleet", "Account", "FAQ"],
        "copyright": "© 2026 Scoot Bali. All rights reserved.",
    },
    "home": {
        "hero": {
            "badge": "Premium Scooter Rental · Bali, Indonesia",
            "titleLead": "Bali,",
            "titleAccent": "Your Way.",
            "subtitle": "Premium scooters delivered to your villa. Book in minutes and get live pricing from the backend.",
            "searchFields": [
                {"label": "Delivery Location", "hint": "Your villa or hotel", "icon": "📍"},
                {"label": "Start Date", "hint": "Pick a date", "icon": "📅"},
                {"label": "Duration", "hint": "Flexible rental", "icon": "⏱"},
            ],
            "searchButton": "Search Fleet →",
            "scroll": "SCROLL",
        },
        "stats": [
            {"value": "2,400+", "label": "Happy Riders"},
            {"value": "4.9 ★", "label": "Avg. Rating"},
            {"value": "< 1hr", "label": "Delivery"},
            {"value": "24 / 7", "label": "Support"},
        ],
        "fleet": {
            "eyebrow": "Our Fleet",
            "title": "Popular Rides",
            "cta": "View All Fleet →",
        },
        "process": {
            "eyebrow": "Process",
            "title": "Book in 3 Steps",
            "subtitle": "From selection to delivery with live backend data.",
            "steps": [
                {
                    "n": "01",
                    "title": "Choose & Book",
                    "desc": "Browse the live fleet, compare prices, and reserve your scooter in a few clicks.",
                    "icon": "🛵",
                    "dark": False,
                },
                {
                    "n": "02",
                    "title": "We Deliver",
                    "desc": "Select your area and address. Delivery details and pricing come directly from the backend.",
                    "icon": "📍",
                    "dark": True,
                },
                {
                    "n": "03",
                    "title": "Ride Bali",
                    "desc": "Track your booking from your account and enjoy a smooth island ride.",
                    "icon": "✨",
                    "dark": False,
                },
            ],
        },
        "why": {
            "eyebrow": "Why Scoot Bali",
            "title": "Rental, reinvented.",
            "features": [
                {
                    "icon": "⚡",
                    "title": "Live Availability",
                    "desc": "The fleet page reflects backend availability and pricing instead of static mock data.",
                },
                {
                    "icon": "🚗",
                    "title": "Villa Delivery",
                    "desc": "Choose a delivery zone and provide your address during checkout.",
                },
                {
                    "icon": "🛡️",
                    "title": "Clear Pricing",
                    "desc": "Rental, add-ons, delivery, and totals are recalculated from the server.",
                },
                {
                    "icon": "📱",
                    "title": "Account Tracking",
                    "desc": "Sign in to see bookings, profile data, notifications, and uploaded documents.",
                },
            ],
            "lifestyleEyebrow": "live backend connection",
            "lifestyleLabel": "Bookings, pricing, and content synced",
            "ratingBadge": "reviews",
        },
        "reviews": {
            "eyebrow": "Reviews",
            "title": "Loved Worldwide",
            "items": [
                {
                    "name": "Sarah M.",
                    "country": "Australia",
                    "flag": "🇦🇺",
                    "rating": 5,
                    "text": "Absolutely flawless from booking to delivery. The scooter was spotless and the whole process felt premium.",
                    "avatar": "SM",
                },
                {
                    "name": "Alex K.",
                    "country": "Russia",
                    "flag": "🇷🇺",
                    "rating": 5,
                    "text": "Лучший прокат на Бали. Всё быстро, понятно и без лишней переписки.",
                    "avatar": "AK",
                },
                {
                    "name": "Mei W.",
                    "country": "China",
                    "flag": "🇨🇳",
                    "rating": 5,
                    "text": "预订流程非常顺畅，送车也很准时，体验非常好。",
                    "avatar": "MW",
                },
                {
                    "name": "James L.",
                    "country": "United Kingdom",
                    "flag": "🇬🇧",
                    "rating": 5,
                    "text": "Great service, transparent pricing, and a much better experience than static rental sites.",
                    "avatar": "JL",
                },
            ],
        },
        "faq": {
            "eyebrow": "FAQ",
            "title": "Questions? We answer.",
            "subtitle": "Need help before you book? Message us and we will guide you through the process.",
            "button": "Open WhatsApp ↗",
            "items": [
                {
                    "q": "Do I need an international driving license?",
                    "a": "Yes. A valid motorcycle license or International Driving Permit is strongly recommended for riding legally in Bali.",
                },
                {
                    "q": "What is included in the rental price?",
                    "a": "Base rental pricing comes from the backend. Helmets, delivery fees, and selected add-ons are clearly shown before confirmation.",
                },
                {
                    "q": "How does delivery work?",
                    "a": "Choose your area, enter the address, and the checkout will use live delivery zones from the backend.",
                },
                {
                    "q": "Can I manage my booking later?",
                    "a": "Yes. Once you sign in or create an account during checkout, your bookings are visible in the account page.",
                },
            ],
        },
    },
    "catalog": {
        "title": "Our Fleet",
        "subtitle": "premium vehicles available across Bali",
        "filtersTitle": "Filters",
        "vehicleType": "Vehicle Type",
        "maxPrice": "Max Price",
        "availability": "Availability",
        "availableNowOnly": "Available Now Only",
        "resetAll": "Reset All",
        "vehiclesFound": "vehicles found",
        "emptyTitle": "No vehicles match",
        "emptyBody": "Try adjusting your filters.",
        "clearFilters": "Clear Filters",
    },
    "detail": {
        "notFoundTitle": "Scooter not found",
        "notFoundBody": "The vehicle you requested is no longer available or the link is invalid.",
        "backToFleet": "Back to Fleet",
        "breadcrumbs": {
            "home": "Home",
            "fleet": "Fleet",
        },
        "tabs": {
            "specs": "Specs",
            "conditions": "Conditions",
            "description": "Description",
        },
        "conditions": {
            "minimumAge": "Minimum age",
            "minimumAgeValue": "18+ with a valid driving license",
            "deposit": "Deposit",
            "depositValue": "Rp {deposit} refundable security deposit",
            "fuelPolicy": "Fuel policy",
            "fuelPolicyValue": "Return the scooter with the same fuel level.",
            "cancellation": "Cancellation",
            "cancellationValue": "Free cancellation up to 24 hours before delivery.",
            "extension": "Extension",
            "extensionValue": "Extensions are possible based on availability.",
        },
        "addonsTitle": "Add-ons",
        "addonsSubtitle": "Enhance your ride and include extras in the live booking total.",
        "checkIn": "Check-In",
        "checkOut": "Check-Out",
        "deliveryLocation": "Delivery Location",
        "selectDate": "Select date",
        "addressPlaceholder": "Your villa or hotel address",
        "reserveNow": "Reserve Now →",
        "freeCancellation": "Free cancellation · Secure booking flow",
        "delivery": "Delivery",
        "summaryTotal": "Total ({days} days)",
        "secureText": "Secure booking · Synced with backend pricing",
        "reviews": "reviews",
    },
    "booking": {
        "unavailableTitle": "Booking unavailable",
        "unavailableBody": "Select a scooter from the fleet first, then continue to checkout.",
        "goToFleet": "Go to Fleet",
        "confirmedTitle": "Booking Confirmed!",
        "bookingId": "Booking ID",
        "confirmationBody": "Your {scooter} will be prepared for delivery. You can review the booking details in your account.",
        "summaryLabels": {
            "vehicle": "Vehicle",
            "duration": "Duration",
            "delivery": "Delivery",
            "total": "Total",
        },
        "steps": ["Dates & Delivery", "Add-ons", "Payment"],
        "title": "Complete Booking",
        "rentalDatesTitle": "Rental Dates",
        "startDate": "Start Date",
        "endDate": "End Date",
        "deliveryTime": "Delivery Time",
        "deliveryAddressTitle": "Delivery Address",
        "areaZone": "Area / Zone",
        "selectArea": "Select your area...",
        "fullAddress": "Full Address",
        "addressPlaceholder": "Villa name, street number, Banjar, area...",
        "addonsTitle": "Add-ons",
        "addonsSubtitle": "Selected add-ons are included in live pricing.",
        "paymentTitle": "Payment Method",
        "contactTitle": "Contact Details",
        "fullName": "Full Name",
        "email": "Email",
        "phone": "Phone",
        "cardholderName": "Cardholder Name",
        "cardNumber": "Card Number",
        "expiry": "Expiry",
        "cvv": "CVV",
        "onlineCardText": "Pay securely online to confirm instantly.",
        "cashText": "Pay our rider upon delivery. Final totals still come from the backend pricing engine.",
        "cardOnDeliveryText": "Reserve now and pay by card when the scooter is delivered.",
        "complete": "Complete Booking",
        "processing": "Processing...",
        "summaryTitle": "Booking Summary",
        "helmetIncluded": "Helmet",
        "createdAccount": "We created your account automatically so you can manage this booking.",
        "existingEmailError": "This email is already registered. Please sign in first on the account page.",
        "pendingTitle": "Booking Created",
        "pendingBody": "Your {scooter} is reserved. Complete payment to confirm the booking.",
        "paymentSucceeded": "Payment completed",
        "paymentPending": "Payment pending",
        "openPayment": "Open payment",
        "detailsRequired": "Please complete dates and delivery details first.",
        "contactRequired": "Please provide your contact details.",
        "submitError": "Booking failed. Please try again.",
    },
    "account": {
        "guestTitle": "Your Account",
        "guestBody": "Sign in or create an account to manage bookings, documents, notifications, and profile details.",
        "loginTab": "Sign In",
        "registerTab": "Create Account",
        "email": "Email",
        "password": "Password",
        "fullName": "Full Name",
        "phone": "Phone",
        "signIn": "Sign In",
        "register": "Create Account",
        "bookings": "My Bookings",
        "documents": "Documents",
        "notifications": "Notifications",
        "profile": "Profile",
        "newBooking": "+ New Booking",
        "noBookings": "No bookings yet.",
        "noDocuments": "No documents uploaded yet.",
        "noNotifications": "No notifications yet.",
        "uploadDocument": "Upload Document",
        "saveProfile": "Save Changes",
        "profileSaved": "Profile saved.",
        "logout": "Log Out",
        "documentType": "Document Type",
        "documentFile": "File",
        "bookingDates": "Dates",
        "bookingZone": "Zone",
        "bookingTotal": "Total",
        "bookingStatus": "Status",
        "markRead": "Mark all as read",
        "country": "Country",
        "language": "Language",
        "currency": "Currency",
        "payNow": "Pay now",
        "openPayment": "Open payment",
        "cancelBookingAction": "Cancel booking",
        "paymentStatus": "Payment Status",
        "paymentMethod": "Payment Method",
        "paymentPending": "Payment is still pending.",
        "paymentStarted": "Payment started. Continue in the payment window.",
        "paymentSucceeded": "Payment completed.",
        "paymentFailed": "Payment failed.",
        "bookingCancelled": "Booking cancelled.",
        "viewDocument": "View document",
        "uploadedAt": "Uploaded",
        "documentUploaded": "Document uploaded.",
    },
}


SITE_CONTENT_OVERRIDES = {
    "ru": {
        "common": {
            "loading": "Загружаю данные с backend...",
            "retry": "Повторить",
            "back": "Назад",
            "continue": "Продолжить",
            "save": "Сохранить",
            "cancel": "Отмена",
            "signOut": "Выйти",
            "free": "Бесплатно",
            "included": "Включено",
            "secure": "Безопасно",
            "perDay": "в день",
            "days": "дней",
            "day": "день",
            "vehiclePhoto": "фото транспорта",
            "unknownError": "Не удалось загрузить актуальные данные.",
            "availability": {
                "available": "Доступно",
                "booked": "Занято",
            },
            "types": {
                "all": "Все типы",
                "scooter": "Скутер",
                "maxi": "Макси-скутер",
                "moto": "Мотоцикл",
            },
            "sort": {
                "popular": "Популярные",
                "price_asc": "Цена: ниже → выше",
                "price_desc": "Цена: выше → ниже",
                "rating": "По рейтингу",
            },
            "paymentMethods": {
                "online_card": "Карта онлайн",
                "cash_on_delivery": "Наличные при доставке",
                "card_on_delivery": "Карта при доставке",
            },
            "documentTypes": {
                "passport": "Паспорт",
                "driver_license": "Водительские права",
                "selfie": "Селфи с документом",
            },
            "bookingStatuses": {
                "created": "Создано",
                "pending_payment": "Ожидает оплаты",
                "paid": "Оплачено",
                "confirmed": "Подтверждено",
                "delivery": "Доставляется",
                "active": "Активно",
                "completed": "Завершено",
                "cancelled": "Отменено",
            },
            "documentStatuses": {
                "not_uploaded": "Не загружено",
                "pending": "На проверке",
                "approved": "Подтверждено",
                "rejected": "Отклонено",
            },
            "specLabels": {
                "engine": "Двигатель",
                "transmission": "Трансмиссия",
                "fuel_consumption": "Расход топлива",
                "year": "Год",
                "trunk": "Багажник",
                "helmets_count": "Шлемы",
                "color": "Цвет",
            },
        },
        "nav": {
            "fleet": "Парк",
            "howItWorks": "Как это работает",
            "locations": "Локации",
            "faq": "FAQ",
            "signIn": "Войти",
            "account": "Аккаунт",
            "bookNow": "Забронировать",
        },
        "footer": {
            "description": "Премиальный прокат скутеров на Бали. Доставим к вашей двери, полностью готовыми к поездке.",
            "columns": [
                {
                    "title": "Парк",
                    "links": ["Скутеры", "Макси-скутеры", "Мотоциклы", "Все модели"],
                },
                {
                    "title": "Компания",
                    "links": ["О нас", "Как это работает", "Локации", "Поддержка"],
                },
                {
                    "title": "Поддержка",
                    "links": ["WhatsApp", "FAQ", "Условия", "Политика конфиденциальности"],
                },
            ],
            "bottomLinks": ["Парк", "Аккаунт", "FAQ"],
            "copyright": "© 2026 Scoot Bali. Все права защищены.",
        },
        "home": {
            "hero": {
                "badge": "Премиальный прокат скутеров · Бали, Индонезия",
                "titleLead": "Бали,",
                "titleAccent": "по-твоему.",
                "subtitle": "Премиальные скутеры с доставкой до вашей виллы. Бронирование за пару минут с живыми данными из backend.",
                "searchFields": [
                    {"label": "Место доставки", "hint": "Вилла или отель", "icon": "📍"},
                    {"label": "Дата начала", "hint": "Выберите дату", "icon": "📅"},
                    {"label": "Срок аренды", "hint": "Гибкая аренда", "icon": "⏱"},
                ],
                "searchButton": "Смотреть парк →",
                "scroll": "ЛИСТАЙ",
            },
            "fleet": {
                "eyebrow": "Наш парк",
                "title": "Популярные модели",
                "cta": "Смотреть весь парк →",
            },
            "process": {
                "eyebrow": "Процесс",
                "title": "Бронирование в 3 шага",
                "subtitle": "От выбора до доставки с живыми данными от backend.",
                "steps": [
                    {
                        "n": "01",
                        "title": "Выберите и забронируйте",
                        "desc": "Откройте актуальный парк, сравните цены и оформите бронь за пару кликов.",
                        "icon": "🛵",
                        "dark": False,
                    },
                    {
                        "n": "02",
                        "title": "Мы доставим",
                        "desc": "Выберите район и адрес. Стоимость и детали доставки приходят напрямую с сервера.",
                        "icon": "📍",
                        "dark": True,
                    },
                    {
                        "n": "03",
                        "title": "Катайтесь по Бали",
                        "desc": "Следите за бронью в аккаунте и наслаждайтесь поездкой по острову.",
                        "icon": "✨",
                        "dark": False,
                    },
                ],
            },
            "why": {
                "eyebrow": "Почему Scoot Bali",
                "title": "Прокат по-новому.",
                "features": [
                    {
                        "icon": "⚡",
                        "title": "Живая доступность",
                        "desc": "Каталог показывает реальные цены и доступность, а не статичные моки.",
                    },
                    {
                        "icon": "🚗",
                        "title": "Доставка до виллы",
                        "desc": "Выберите зону доставки и введите адрес прямо во время оформления.",
                    },
                    {
                        "icon": "🛡️",
                        "title": "Понятная цена",
                        "desc": "Аренда, допы, доставка и итог считаются на сервере.",
                    },
                    {
                        "icon": "📱",
                        "title": "Управление из аккаунта",
                        "desc": "После входа вы видите брони, профиль, уведомления и документы.",
                    },
                ],
                "lifestyleEyebrow": "backend подключён",
                "lifestyleLabel": "Брони, цены и контент синхронизированы",
                "ratingBadge": "отзывов",
            },
            "reviews": {
                "eyebrow": "Отзывы",
                "title": "Нас любят по всему миру",
                "items": [
                    {
                        "name": "Sarah M.",
                        "country": "Австралия",
                        "flag": "🇦🇺",
                        "rating": 5,
                        "text": "Всё прошло идеально от бронирования до доставки. Скутер был в отличном состоянии, сервис действительно премиальный.",
                        "avatar": "SM",
                    },
                    {
                        "name": "Alex K.",
                        "country": "Россия",
                        "flag": "🇷🇺",
                        "rating": 5,
                        "text": "Лучший прокат на Бали. Всё быстро, понятно и без лишней переписки.",
                        "avatar": "AK",
                    },
                    {
                        "name": "Mei W.",
                        "country": "Китай",
                        "flag": "🇨🇳",
                        "rating": 5,
                        "text": "预订流程非常顺畅，送车也很准时，体验非常好。",
                        "avatar": "MW",
                    },
                    {
                        "name": "James L.",
                        "country": "Великобритания",
                        "flag": "🇬🇧",
                        "rating": 5,
                        "text": "Отличный сервис, прозрачные цены и заметно лучший опыт, чем у обычных сайтов проката.",
                        "avatar": "JL",
                    },
                ],
            },
            "faq": {
                "eyebrow": "FAQ",
                "title": "Есть вопросы? Ответим.",
                "subtitle": "Нужна помощь перед бронированием? Напишите нам, и мы подскажем.",
                "button": "Открыть WhatsApp ↗",
                "items": [
                    {
                        "q": "Нужны ли международные права?",
                        "a": "Да. Для легальной езды по Бали очень желательно иметь права на мотоцикл или международное водительское удостоверение.",
                    },
                    {
                        "q": "Что входит в стоимость аренды?",
                        "a": "Базовая цена приходит с backend. Шлемы, доставка и выбранные допы видны до подтверждения брони.",
                    },
                    {
                        "q": "Как работает доставка?",
                        "a": "Выберите район, введите адрес, и checkout использует реальные зоны доставки с сервера.",
                    },
                    {
                        "q": "Можно ли потом управлять бронью?",
                        "a": "Да. После входа или создания аккаунта во время оформления бронь появится в аккаунте.",
                    },
                ],
            },
        },
        "catalog": {
            "title": "Наш парк",
            "subtitle": "премиальных моделей доступны по всему Бали",
            "filtersTitle": "Фильтры",
            "vehicleType": "Тип транспорта",
            "maxPrice": "Макс. цена",
            "availability": "Доступность",
            "availableNowOnly": "Только доступные сейчас",
            "resetAll": "Сбросить всё",
            "vehiclesFound": "моделей найдено",
            "emptyTitle": "Ничего не найдено",
            "emptyBody": "Попробуйте изменить фильтры.",
            "clearFilters": "Очистить фильтры",
        },
        "detail": {
            "notFoundTitle": "Скутер не найден",
            "notFoundBody": "Запрошенный транспорт больше недоступен или ссылка неверна.",
            "backToFleet": "Назад в парк",
            "breadcrumbs": {
                "home": "Главная",
                "fleet": "Парк",
            },
            "tabs": {
                "specs": "Характеристики",
                "conditions": "Условия",
                "description": "Описание",
            },
            "conditions": {
                "minimumAge": "Минимальный возраст",
                "minimumAgeValue": "18+ и действующие права",
                "deposit": "Депозит",
                "depositValue": "Возвратный депозит Rp {deposit}",
                "fuelPolicy": "Топливо",
                "fuelPolicyValue": "Верните скутер с тем же уровнем топлива.",
                "cancellation": "Отмена",
                "cancellationValue": "Бесплатная отмена за 24 часа до доставки.",
                "extension": "Продление",
                "extensionValue": "Продление возможно при наличии транспорта.",
            },
            "addonsTitle": "Дополнения",
            "addonsSubtitle": "Улучшите поездку и сразу включите допы в итоговую цену.",
            "checkIn": "Начало",
            "checkOut": "Окончание",
            "deliveryLocation": "Адрес доставки",
            "selectDate": "Выберите дату",
            "addressPlaceholder": "Адрес вашей виллы или отеля",
            "reserveNow": "Забронировать →",
            "freeCancellation": "Бесплатная отмена · Безопасное бронирование",
            "delivery": "Доставка",
            "summaryTotal": "Итого ({days} дней)",
            "secureText": "Безопасное бронирование · Цена синхронизирована с backend",
            "reviews": "отзывов",
        },
        "booking": {
            "unavailableTitle": "Бронирование недоступно",
            "unavailableBody": "Сначала выберите скутер в каталоге, а затем переходите к оформлению.",
            "goToFleet": "Перейти в парк",
            "confirmedTitle": "Бронирование подтверждено!",
            "bookingId": "Номер брони",
            "confirmationBody": "Ваш {scooter} подготовят к доставке. Детали брони будут доступны в аккаунте.",
            "summaryLabels": {
                "vehicle": "Транспорт",
                "duration": "Срок",
                "delivery": "Доставка",
                "total": "Итого",
            },
            "steps": ["Даты и доставка", "Допы", "Оплата"],
            "title": "Оформление бронирования",
            "rentalDatesTitle": "Даты аренды",
            "startDate": "Дата начала",
            "endDate": "Дата окончания",
            "deliveryTime": "Время доставки",
            "deliveryAddressTitle": "Адрес доставки",
            "areaZone": "Район / зона",
            "selectArea": "Выберите район...",
            "fullAddress": "Полный адрес",
            "addressPlaceholder": "Название виллы, номер улицы, Banjar, район...",
            "addonsTitle": "Дополнения",
            "addonsSubtitle": "Выбранные допы включаются в живой расчёт цены.",
            "paymentTitle": "Способ оплаты",
            "contactTitle": "Контактные данные",
            "fullName": "Полное имя",
            "email": "Email",
            "phone": "Телефон",
            "cardholderName": "Имя владельца карты",
            "cardNumber": "Номер карты",
            "expiry": "Срок действия",
            "cvv": "CVV",
            "onlineCardText": "Оплатите онлайн и получите мгновенное подтверждение.",
            "cashText": "Оплатите водителю при доставке. Итог всё равно считается на сервере.",
            "cardOnDeliveryText": "Забронируйте сейчас и оплатите картой при доставке.",
            "complete": "Завершить бронирование",
            "processing": "Обрабатываем...",
            "summaryTitle": "Сводка бронирования",
            "helmetIncluded": "Шлем",
            "createdAccount": "Мы автоматически создали вам аккаунт, чтобы вы могли управлять бронью.",
            "existingEmailError": "Этот email уже зарегистрирован. Сначала войдите через страницу аккаунта.",
            "pendingTitle": "Бронирование создано",
            "pendingBody": "Ваш {scooter} зарезервирован. Завершите оплату, чтобы подтвердить бронь.",
            "paymentSucceeded": "Оплата прошла успешно",
            "paymentPending": "Оплата ожидается",
            "openPayment": "Открыть оплату",
            "detailsRequired": "Сначала заполните даты и адрес доставки.",
            "contactRequired": "Укажите ваши контактные данные.",
            "submitError": "Не удалось оформить бронирование. Попробуйте ещё раз.",
        },
        "account": {
            "guestTitle": "Ваш аккаунт",
            "guestBody": "Войдите или создайте аккаунт, чтобы управлять бронированиями, документами, уведомлениями и профилем.",
            "loginTab": "Вход",
            "registerTab": "Регистрация",
            "email": "Email",
            "password": "Пароль",
            "fullName": "Полное имя",
            "phone": "Телефон",
            "signIn": "Войти",
            "register": "Создать аккаунт",
            "bookings": "Мои брони",
            "documents": "Документы",
            "notifications": "Уведомления",
            "profile": "Профиль",
            "newBooking": "+ Новая бронь",
            "noBookings": "Пока нет бронирований.",
            "noDocuments": "Документы ещё не загружены.",
            "noNotifications": "Пока нет уведомлений.",
            "uploadDocument": "Загрузить документ",
            "saveProfile": "Сохранить изменения",
            "profileSaved": "Профиль сохранён.",
            "logout": "Выйти",
            "documentType": "Тип документа",
            "documentFile": "Файл",
            "bookingDates": "Даты",
            "bookingZone": "Зона",
            "bookingTotal": "Итого",
            "bookingStatus": "Статус",
            "markRead": "Отметить всё как прочитанное",
            "country": "Страна",
            "language": "Язык",
            "currency": "Валюта",
            "payNow": "Оплатить",
            "openPayment": "Открыть оплату",
            "cancelBookingAction": "Отменить бронь",
            "paymentStatus": "Статус оплаты",
            "paymentMethod": "Способ оплаты",
            "paymentPending": "Оплата всё ещё ожидается.",
            "paymentStarted": "Оплата создана. Продолжите в окне оплаты.",
            "paymentSucceeded": "Оплата прошла успешно.",
            "paymentFailed": "Оплата не прошла.",
            "bookingCancelled": "Бронь отменена.",
            "viewDocument": "Открыть документ",
            "uploadedAt": "Загружено",
            "documentUploaded": "Документ загружен.",
        },
    },
    "zh": {
        "common": {
            "loading": "正在从后端加载数据...",
            "retry": "重试",
            "back": "返回",
            "continue": "继续",
            "save": "保存",
            "signOut": "退出",
            "free": "免费",
            "included": "已包含",
            "secure": "安全",
            "perDay": "每天",
            "days": "天",
            "day": "天",
            "availability": {"available": "可租", "booked": "已预订"},
            "types": {"all": "全部类型", "scooter": "踏板车", "maxi": "大型踏板", "moto": "摩托车"},
            "paymentMethods": {"online_card": "在线刷卡", "cash_on_delivery": "送达付现", "card_on_delivery": "送达刷卡"},
            "documentTypes": {"passport": "护照", "driver_license": "驾照", "selfie": "证件自拍"},
        },
        "nav": {"fleet": "车队", "howItWorks": "流程", "locations": "区域", "faq": "常见问题", "signIn": "登录", "account": "账户", "bookNow": "立即预订"},
        "home": {
            "hero": {
                "badge": "巴厘岛高端摩托租赁",
                "titleLead": "巴厘岛，",
                "titleAccent": "随你去骑。",
                "subtitle": "别墅配送，高端车型，所有价格与库存都直接来自后端。",
                "searchFields": [
                    {"label": "配送地点", "hint": "别墅或酒店", "icon": "📍"},
                    {"label": "开始日期", "hint": "选择日期", "icon": "📅"},
                    {"label": "租期", "hint": "灵活租期", "icon": "⏱"},
                ],
                "searchButton": "查看车队 →",
                "scroll": "下滑",
            },
        },
        "catalog": {
            "title": "我们的车队",
            "subtitle": "台高端车辆覆盖整个巴厘岛",
            "filtersTitle": "筛选",
            "vehicleType": "车辆类型",
            "maxPrice": "最高价格",
            "availability": "可用性",
            "availableNowOnly": "仅看当前可租",
            "resetAll": "重置",
            "vehiclesFound": "台车辆",
            "emptyTitle": "没有匹配车辆",
            "emptyBody": "请调整筛选条件。",
            "clearFilters": "清除筛选",
        },
        "detail": {
            "notFoundTitle": "未找到车辆",
            "notFoundBody": "该车辆当前不可用或链接无效。",
            "backToFleet": "返回车队",
            "breadcrumbs": {"home": "首页", "fleet": "车队"},
            "tabs": {"specs": "参数", "conditions": "租赁条件", "description": "介绍"},
            "addonsTitle": "附加服务",
            "addonsSubtitle": "将附加服务加入实时总价。",
            "checkIn": "开始",
            "checkOut": "结束",
            "deliveryLocation": "配送地址",
            "selectDate": "选择日期",
            "addressPlaceholder": "您的别墅或酒店地址",
            "reserveNow": "立即预订 →",
            "freeCancellation": "可免费取消 · 安全预订",
            "delivery": "配送",
            "summaryTotal": "总计（{days}天）",
            "secureText": "安全预订 · 价格与后端同步",
            "reviews": "条评价",
        },
        "booking": {
            "unavailableTitle": "暂时无法预订",
            "unavailableBody": "请先在车队页面选择一辆车。",
            "goToFleet": "前往车队",
            "confirmedTitle": "预订已确认！",
            "bookingId": "订单号",
            "confirmationBody": "您的 {scooter} 已安排配送，详情可在账户中查看。",
            "steps": ["日期与配送", "附加服务", "付款"],
            "title": "完成预订",
            "rentalDatesTitle": "租赁日期",
            "startDate": "开始日期",
            "endDate": "结束日期",
            "deliveryTime": "配送时间",
            "deliveryAddressTitle": "配送地址",
            "areaZone": "区域",
            "selectArea": "请选择区域...",
            "fullAddress": "详细地址",
            "addressPlaceholder": "别墅名称、街道、区域...",
            "addonsTitle": "附加服务",
            "addonsSubtitle": "附加服务会计入实时价格。",
            "paymentTitle": "付款方式",
            "contactTitle": "联系信息",
            "fullName": "姓名",
            "email": "邮箱",
            "phone": "电话",
            "cardholderName": "持卡人姓名",
            "cardNumber": "卡号",
            "expiry": "到期时间",
            "cvv": "CVV",
            "onlineCardText": "在线安全支付并即时确认。",
            "cashText": "车辆送达时现金支付，总价仍由后端计算。",
            "cardOnDeliveryText": "先预订，送达时刷卡付款。",
            "complete": "完成预订",
            "processing": "处理中...",
            "summaryTitle": "订单摘要",
            "helmetIncluded": "头盔",
            "createdAccount": "我们已自动为您创建账户，方便您管理订单。",
            "existingEmailError": "此邮箱已注册，请先登录。",
            "pendingTitle": "订单已创建",
            "pendingBody": "您的 {scooter} 已保留。请完成付款以确认订单。",
            "paymentSucceeded": "付款已完成",
            "paymentPending": "付款待处理",
            "openPayment": "打开付款页面",
            "detailsRequired": "请先填写日期和送车信息。",
            "contactRequired": "请填写您的联系方式。",
            "submitError": "预订失败，请重试。",
        },
        "account": {
            "guestTitle": "您的账户",
            "guestBody": "登录或创建账户以管理订单、证件、通知和个人资料。",
            "loginTab": "登录",
            "registerTab": "注册",
            "email": "邮箱",
            "password": "密码",
            "fullName": "姓名",
            "phone": "电话",
            "signIn": "登录",
            "register": "创建账户",
            "bookings": "我的订单",
            "documents": "证件",
            "notifications": "通知",
            "profile": "个人资料",
            "newBooking": "+ 新预订",
            "noBookings": "暂时没有订单。",
            "noDocuments": "暂未上传证件。",
            "noNotifications": "暂无通知。",
            "uploadDocument": "上传证件",
            "saveProfile": "保存更改",
            "profileSaved": "资料已保存。",
            "logout": "退出登录",
            "documentType": "证件类型",
            "documentFile": "文件",
            "markRead": "全部标记为已读",
            "country": "国家",
            "language": "语言",
            "currency": "货币",
            "payNow": "立即付款",
            "openPayment": "打开付款",
            "cancelBookingAction": "取消订单",
            "paymentStatus": "付款状态",
            "paymentMethod": "付款方式",
            "paymentPending": "付款仍在处理中。",
            "paymentStarted": "付款已发起，请在付款窗口继续。",
            "paymentSucceeded": "付款成功。",
            "paymentFailed": "付款失败。",
            "bookingCancelled": "订单已取消。",
            "viewDocument": "查看证件",
            "uploadedAt": "上传时间",
            "documentUploaded": "证件已上传。",
        },
    },
    "id": {
        "common": {
            "loading": "Memuat data dari backend...",
            "retry": "Coba lagi",
            "back": "Kembali",
            "continue": "Lanjut",
            "save": "Simpan",
            "signOut": "Keluar",
            "free": "Gratis",
            "included": "Termasuk",
            "secure": "Aman",
            "perDay": "per hari",
            "days": "hari",
            "day": "hari",
            "availability": {"available": "Tersedia", "booked": "Terpesan"},
            "types": {"all": "Semua Tipe", "scooter": "Skuter", "maxi": "Maxi Scooter", "moto": "Motor"},
            "paymentMethods": {"online_card": "Kartu Online", "cash_on_delivery": "Bayar Tunai Saat Antar", "card_on_delivery": "Kartu Saat Antar"},
            "documentTypes": {"passport": "Paspor", "driver_license": "SIM", "selfie": "Selfie Dokumen"},
        },
        "nav": {"fleet": "Armada", "howItWorks": "Cara Kerja", "locations": "Lokasi", "faq": "FAQ", "signIn": "Masuk", "account": "Akun", "bookNow": "Pesan Sekarang"},
        "home": {
            "hero": {
                "badge": "Rental skuter premium di Bali",
                "titleLead": "Bali,",
                "titleAccent": "sesuai caramu.",
                "subtitle": "Skuter premium diantar ke villa Anda, dengan harga dan ketersediaan langsung dari backend.",
                "searchFields": [
                    {"label": "Lokasi Antar", "hint": "Villa atau hotel Anda", "icon": "📍"},
                    {"label": "Tanggal Mulai", "hint": "Pilih tanggal", "icon": "📅"},
                    {"label": "Durasi", "hint": "Durasi fleksibel", "icon": "⏱"},
                ],
                "searchButton": "Lihat Armada →",
                "scroll": "GESER",
            },
        },
        "catalog": {
            "title": "Armada Kami",
            "subtitle": "kendaraan premium tersedia di seluruh Bali",
            "filtersTitle": "Filter",
            "vehicleType": "Tipe Kendaraan",
            "maxPrice": "Harga Maksimal",
            "availability": "Ketersediaan",
            "availableNowOnly": "Hanya yang tersedia sekarang",
            "resetAll": "Reset",
            "vehiclesFound": "kendaraan ditemukan",
            "emptyTitle": "Tidak ada kendaraan yang cocok",
            "emptyBody": "Coba ubah filter Anda.",
            "clearFilters": "Hapus Filter",
        },
        "detail": {
            "notFoundTitle": "Skuter tidak ditemukan",
            "notFoundBody": "Kendaraan ini sudah tidak tersedia atau tautannya tidak valid.",
            "backToFleet": "Kembali ke Armada",
            "breadcrumbs": {"home": "Beranda", "fleet": "Armada"},
            "tabs": {"specs": "Spesifikasi", "conditions": "Ketentuan", "description": "Deskripsi"},
            "addonsTitle": "Add-on",
            "addonsSubtitle": "Tambahkan layanan ekstra ke total booking langsung.",
            "checkIn": "Mulai",
            "checkOut": "Selesai",
            "deliveryLocation": "Lokasi Antar",
            "selectDate": "Pilih tanggal",
            "addressPlaceholder": "Alamat villa atau hotel Anda",
            "reserveNow": "Pesan Sekarang →",
            "freeCancellation": "Pembatalan gratis · Booking aman",
            "delivery": "Pengantaran",
            "summaryTotal": "Total ({days} hari)",
            "secureText": "Booking aman · Harga sinkron dengan backend",
            "reviews": "ulasan",
        },
        "booking": {
            "unavailableTitle": "Booking belum tersedia",
            "unavailableBody": "Pilih dulu skuter dari armada, lalu lanjut ke checkout.",
            "goToFleet": "Buka Armada",
            "confirmedTitle": "Booking Berhasil!",
            "bookingId": "ID Booking",
            "confirmationBody": "{scooter} Anda sedang diproses untuk pengantaran. Detailnya bisa dilihat di akun.",
            "steps": ["Tanggal & Antar", "Add-on", "Pembayaran"],
            "title": "Selesaikan Booking",
            "rentalDatesTitle": "Tanggal Rental",
            "startDate": "Tanggal Mulai",
            "endDate": "Tanggal Selesai",
            "deliveryTime": "Jam Antar",
            "deliveryAddressTitle": "Alamat Antar",
            "areaZone": "Area / Zona",
            "selectArea": "Pilih area Anda...",
            "fullAddress": "Alamat Lengkap",
            "addressPlaceholder": "Nama villa, jalan, banjar, area...",
            "addonsTitle": "Add-on",
            "addonsSubtitle": "Add-on masuk ke perhitungan harga live.",
            "paymentTitle": "Metode Pembayaran",
            "contactTitle": "Detail Kontak",
            "fullName": "Nama Lengkap",
            "email": "Email",
            "phone": "Telepon",
            "cardholderName": "Nama pada Kartu",
            "cardNumber": "Nomor Kartu",
            "expiry": "Masa Berlaku",
            "cvv": "CVV",
            "onlineCardText": "Bayar online dengan aman untuk konfirmasi instan.",
            "cashText": "Bayar tunai saat motor diantar. Total tetap dihitung dari backend.",
            "cardOnDeliveryText": "Booking sekarang dan bayar kartu saat pengantaran.",
            "complete": "Selesaikan Booking",
            "processing": "Memproses...",
            "summaryTitle": "Ringkasan Booking",
            "helmetIncluded": "Helm",
            "createdAccount": "Akun Anda dibuat otomatis agar booking bisa dikelola.",
            "existingEmailError": "Email ini sudah terdaftar. Silakan masuk dulu.",
            "pendingTitle": "Booking dibuat",
            "pendingBody": "{scooter} Anda sudah dicadangkan. Selesaikan pembayaran untuk konfirmasi booking.",
            "paymentSucceeded": "Pembayaran berhasil",
            "paymentPending": "Pembayaran menunggu",
            "openPayment": "Buka pembayaran",
            "detailsRequired": "Lengkapi dulu tanggal dan detail pengantaran.",
            "contactRequired": "Mohon isi detail kontak Anda.",
            "submitError": "Booking gagal. Silakan coba lagi.",
        },
        "account": {
            "guestTitle": "Akun Anda",
            "guestBody": "Masuk atau buat akun untuk mengelola booking, dokumen, notifikasi, dan profil.",
            "loginTab": "Masuk",
            "registerTab": "Daftar",
            "email": "Email",
            "password": "Kata Sandi",
            "fullName": "Nama Lengkap",
            "phone": "Telepon",
            "signIn": "Masuk",
            "register": "Buat Akun",
            "bookings": "Booking Saya",
            "documents": "Dokumen",
            "notifications": "Notifikasi",
            "profile": "Profil",
            "newBooking": "+ Booking Baru",
            "noBookings": "Belum ada booking.",
            "noDocuments": "Belum ada dokumen diunggah.",
            "noNotifications": "Belum ada notifikasi.",
            "uploadDocument": "Unggah Dokumen",
            "saveProfile": "Simpan Perubahan",
            "profileSaved": "Profil tersimpan.",
            "logout": "Keluar",
            "documentType": "Jenis Dokumen",
            "documentFile": "File",
            "markRead": "Tandai semua sudah dibaca",
            "country": "Negara",
            "language": "Bahasa",
            "currency": "Mata Uang",
            "payNow": "Bayar sekarang",
            "openPayment": "Buka pembayaran",
            "cancelBookingAction": "Batalkan booking",
            "paymentStatus": "Status pembayaran",
            "paymentMethod": "Metode pembayaran",
            "paymentPending": "Pembayaran masih menunggu.",
            "paymentStarted": "Pembayaran dimulai. Lanjutkan di jendela pembayaran.",
            "paymentSucceeded": "Pembayaran berhasil.",
            "paymentFailed": "Pembayaran gagal.",
            "bookingCancelled": "Booking dibatalkan.",
            "viewDocument": "Lihat dokumen",
            "uploadedAt": "Diunggah",
            "documentUploaded": "Dokumen diunggah.",
        },
    },
    "de": {
        "common": {
            "loading": "Backend-Daten werden geladen...",
            "retry": "Erneut versuchen",
            "back": "Zurück",
            "continue": "Weiter",
            "save": "Speichern",
            "signOut": "Abmelden",
            "free": "Kostenlos",
            "included": "Inklusive",
            "secure": "Sicher",
            "perDay": "pro Tag",
            "days": "Tage",
            "day": "Tag",
            "availability": {"available": "Verfügbar", "booked": "Gebucht"},
            "types": {"all": "Alle Typen", "scooter": "Scooter", "maxi": "Maxi-Scooter", "moto": "Motorrad"},
            "paymentMethods": {"online_card": "Online-Karte", "cash_on_delivery": "Bar bei Lieferung", "card_on_delivery": "Karte bei Lieferung"},
            "documentTypes": {"passport": "Reisepass", "driver_license": "Führerschein", "selfie": "Selfie mit Dokument"},
        },
        "nav": {"fleet": "Flotte", "howItWorks": "So funktioniert's", "locations": "Gebiete", "faq": "FAQ", "signIn": "Anmelden", "account": "Konto", "bookNow": "Jetzt buchen"},
        "home": {
            "hero": {
                "badge": "Premium-Scootervermietung auf Bali",
                "titleLead": "Bali,",
                "titleAccent": "auf deine Art.",
                "subtitle": "Premium-Scooter direkt zur Villa geliefert, mit Live-Preisen und Verfügbarkeit aus dem Backend.",
                "searchFields": [
                    {"label": "Lieferort", "hint": "Villa oder Hotel", "icon": "📍"},
                    {"label": "Startdatum", "hint": "Datum wählen", "icon": "📅"},
                    {"label": "Dauer", "hint": "Flexible Mietdauer", "icon": "⏱"},
                ],
                "searchButton": "Flotte ansehen →",
                "scroll": "SCROLLEN",
            },
        },
        "catalog": {
            "title": "Unsere Flotte",
            "subtitle": "Premium-Fahrzeuge auf ganz Bali verfügbar",
            "filtersTitle": "Filter",
            "vehicleType": "Fahrzeugtyp",
            "maxPrice": "Maximalpreis",
            "availability": "Verfügbarkeit",
            "availableNowOnly": "Nur sofort verfügbare",
            "resetAll": "Zurücksetzen",
            "vehiclesFound": "Fahrzeuge gefunden",
            "emptyTitle": "Keine passenden Fahrzeuge",
            "emptyBody": "Passe die Filter an.",
            "clearFilters": "Filter löschen",
        },
        "detail": {
            "notFoundTitle": "Scooter nicht gefunden",
            "notFoundBody": "Dieses Fahrzeug ist nicht mehr verfügbar oder der Link ist ungültig.",
            "backToFleet": "Zurück zur Flotte",
            "breadcrumbs": {"home": "Start", "fleet": "Flotte"},
            "tabs": {"specs": "Daten", "conditions": "Bedingungen", "description": "Beschreibung"},
            "addonsTitle": "Extras",
            "addonsSubtitle": "Füge Extras direkt zum Live-Gesamtpreis hinzu.",
            "checkIn": "Start",
            "checkOut": "Ende",
            "deliveryLocation": "Lieferadresse",
            "selectDate": "Datum wählen",
            "addressPlaceholder": "Adresse deiner Villa oder deines Hotels",
            "reserveNow": "Jetzt reservieren →",
            "freeCancellation": "Kostenlose Stornierung · Sichere Buchung",
            "delivery": "Lieferung",
            "summaryTotal": "Gesamt ({days} Tage)",
            "secureText": "Sichere Buchung · Preis mit Backend synchronisiert",
            "reviews": "Bewertungen",
        },
        "booking": {
            "unavailableTitle": "Buchung nicht verfügbar",
            "unavailableBody": "Wähle zuerst einen Scooter aus der Flotte aus.",
            "goToFleet": "Zur Flotte",
            "confirmedTitle": "Buchung bestätigt!",
            "bookingId": "Buchungsnummer",
            "confirmationBody": "Dein {scooter} wird vorbereitet. Details findest du im Konto.",
            "steps": ["Daten & Lieferung", "Extras", "Zahlung"],
            "title": "Buchung abschließen",
            "rentalDatesTitle": "Mietdaten",
            "startDate": "Startdatum",
            "endDate": "Enddatum",
            "deliveryTime": "Lieferzeit",
            "deliveryAddressTitle": "Lieferadresse",
            "areaZone": "Bereich / Zone",
            "selectArea": "Bereich wählen...",
            "fullAddress": "Vollständige Adresse",
            "addressPlaceholder": "Villa, Straße, Banjar, Bereich...",
            "addonsTitle": "Extras",
            "addonsSubtitle": "Extras werden in die Live-Preisberechnung einbezogen.",
            "paymentTitle": "Zahlungsmethode",
            "contactTitle": "Kontaktdaten",
            "fullName": "Vollständiger Name",
            "email": "E-Mail",
            "phone": "Telefon",
            "cardholderName": "Name auf der Karte",
            "cardNumber": "Kartennummer",
            "expiry": "Gültig bis",
            "cvv": "CVV",
            "onlineCardText": "Sicher online bezahlen und sofort bestätigen.",
            "cashText": "Bei Lieferung bar bezahlen. Der Gesamtpreis kommt trotzdem aus dem Backend.",
            "cardOnDeliveryText": "Jetzt reservieren und bei Lieferung per Karte zahlen.",
            "complete": "Buchung abschließen",
            "processing": "Wird verarbeitet...",
            "summaryTitle": "Buchungsübersicht",
            "helmetIncluded": "Helm",
            "createdAccount": "Wir haben automatisch ein Konto für dich erstellt.",
            "existingEmailError": "Diese E-Mail ist bereits registriert. Bitte zuerst anmelden.",
            "pendingTitle": "Buchung erstellt",
            "pendingBody": "Dein {scooter} ist reserviert. Schließe die Zahlung ab, um die Buchung zu bestätigen.",
            "paymentSucceeded": "Zahlung abgeschlossen",
            "paymentPending": "Zahlung ausstehend",
            "openPayment": "Zahlung öffnen",
            "detailsRequired": "Bitte zuerst Datum und Lieferdetails ausfüllen.",
            "contactRequired": "Bitte gib deine Kontaktdaten an.",
            "submitError": "Buchung fehlgeschlagen. Bitte versuche es erneut.",
        },
        "account": {
            "guestTitle": "Dein Konto",
            "guestBody": "Melde dich an oder erstelle ein Konto, um Buchungen, Dokumente und Profil zu verwalten.",
            "loginTab": "Anmelden",
            "registerTab": "Registrieren",
            "email": "E-Mail",
            "password": "Passwort",
            "fullName": "Vollständiger Name",
            "phone": "Telefon",
            "signIn": "Anmelden",
            "register": "Konto erstellen",
            "bookings": "Meine Buchungen",
            "documents": "Dokumente",
            "notifications": "Benachrichtigungen",
            "profile": "Profil",
            "newBooking": "+ Neue Buchung",
            "noBookings": "Noch keine Buchungen.",
            "noDocuments": "Noch keine Dokumente hochgeladen.",
            "noNotifications": "Noch keine Benachrichtigungen.",
            "uploadDocument": "Dokument hochladen",
            "saveProfile": "Änderungen speichern",
            "profileSaved": "Profil gespeichert.",
            "logout": "Abmelden",
            "documentType": "Dokumenttyp",
            "documentFile": "Datei",
            "markRead": "Alle als gelesen markieren",
            "country": "Land",
            "language": "Sprache",
            "currency": "Währung",
            "payNow": "Jetzt bezahlen",
            "openPayment": "Zahlung öffnen",
            "cancelBookingAction": "Buchung stornieren",
            "paymentStatus": "Zahlungsstatus",
            "paymentMethod": "Zahlungsart",
            "paymentPending": "Die Zahlung ist noch ausstehend.",
            "paymentStarted": "Zahlung gestartet. Bitte im Zahlungsfenster fortfahren.",
            "paymentSucceeded": "Zahlung erfolgreich.",
            "paymentFailed": "Zahlung fehlgeschlagen.",
            "bookingCancelled": "Buchung storniert.",
            "viewDocument": "Dokument ansehen",
            "uploadedAt": "Hochgeladen",
            "documentUploaded": "Dokument hochgeladen.",
        },
    },
    "fr": {
        "common": {
            "loading": "Chargement des données depuis le backend...",
            "retry": "Réessayer",
            "back": "Retour",
            "continue": "Continuer",
            "save": "Enregistrer",
            "signOut": "Se déconnecter",
            "free": "Gratuit",
            "included": "Inclus",
            "secure": "Sécurisé",
            "perDay": "par jour",
            "days": "jours",
            "day": "jour",
            "availability": {"available": "Disponible", "booked": "Réservé"},
            "types": {"all": "Tous les types", "scooter": "Scooter", "maxi": "Maxi-scooter", "moto": "Moto"},
            "paymentMethods": {"online_card": "Carte en ligne", "cash_on_delivery": "Espèces à la livraison", "card_on_delivery": "Carte à la livraison"},
            "documentTypes": {"passport": "Passeport", "driver_license": "Permis de conduire", "selfie": "Selfie avec document"},
        },
        "nav": {"fleet": "Flotte", "howItWorks": "Comment ça marche", "locations": "Zones", "faq": "FAQ", "signIn": "Connexion", "account": "Compte", "bookNow": "Réserver"},
        "home": {
            "hero": {
                "badge": "Location de scooters premium à Bali",
                "titleLead": "Bali,",
                "titleAccent": "à votre façon.",
                "subtitle": "Des scooters premium livrés à votre villa, avec prix et disponibilité en direct depuis le backend.",
                "searchFields": [
                    {"label": "Lieu de livraison", "hint": "Votre villa ou hôtel", "icon": "📍"},
                    {"label": "Date de début", "hint": "Choisir une date", "icon": "📅"},
                    {"label": "Durée", "hint": "Durée flexible", "icon": "⏱"},
                ],
                "searchButton": "Voir la flotte →",
                "scroll": "DÉFILER",
            },
        },
        "catalog": {
            "title": "Notre flotte",
            "subtitle": "véhicules premium disponibles partout à Bali",
            "filtersTitle": "Filtres",
            "vehicleType": "Type de véhicule",
            "maxPrice": "Prix maximum",
            "availability": "Disponibilité",
            "availableNowOnly": "Seulement disponibles maintenant",
            "resetAll": "Réinitialiser",
            "vehiclesFound": "véhicules trouvés",
            "emptyTitle": "Aucun véhicule correspondant",
            "emptyBody": "Essayez de modifier vos filtres.",
            "clearFilters": "Effacer les filtres",
        },
        "detail": {
            "notFoundTitle": "Scooter introuvable",
            "notFoundBody": "Ce véhicule n'est plus disponible ou le lien est invalide.",
            "backToFleet": "Retour à la flotte",
            "breadcrumbs": {"home": "Accueil", "fleet": "Flotte"},
            "tabs": {"specs": "Spécifications", "conditions": "Conditions", "description": "Description"},
            "addonsTitle": "Options",
            "addonsSubtitle": "Ajoutez des options au total en temps réel.",
            "checkIn": "Début",
            "checkOut": "Fin",
            "deliveryLocation": "Adresse de livraison",
            "selectDate": "Choisir une date",
            "addressPlaceholder": "Adresse de votre villa ou hôtel",
            "reserveNow": "Réserver maintenant →",
            "freeCancellation": "Annulation gratuite · Réservation sécurisée",
            "delivery": "Livraison",
            "summaryTotal": "Total ({days} jours)",
            "secureText": "Réservation sécurisée · Prix synchronisé avec le backend",
            "reviews": "avis",
        },
        "booking": {
            "unavailableTitle": "Réservation indisponible",
            "unavailableBody": "Choisissez d'abord un scooter depuis la flotte.",
            "goToFleet": "Voir la flotte",
            "confirmedTitle": "Réservation confirmée !",
            "bookingId": "ID de réservation",
            "confirmationBody": "Votre {scooter} est en préparation. Les détails sont disponibles dans votre compte.",
            "steps": ["Dates & livraison", "Options", "Paiement"],
            "title": "Finaliser la réservation",
            "rentalDatesTitle": "Dates de location",
            "startDate": "Date de début",
            "endDate": "Date de fin",
            "deliveryTime": "Heure de livraison",
            "deliveryAddressTitle": "Adresse de livraison",
            "areaZone": "Zone",
            "selectArea": "Choisissez votre zone...",
            "fullAddress": "Adresse complète",
            "addressPlaceholder": "Nom de la villa, rue, banjar, zone...",
            "addonsTitle": "Options",
            "addonsSubtitle": "Les options sont incluses dans le calcul du prix en direct.",
            "paymentTitle": "Mode de paiement",
            "contactTitle": "Coordonnées",
            "fullName": "Nom complet",
            "email": "E-mail",
            "phone": "Téléphone",
            "cardholderName": "Nom du titulaire",
            "cardNumber": "Numéro de carte",
            "expiry": "Expiration",
            "cvv": "CVV",
            "onlineCardText": "Payez en ligne en toute sécurité pour une confirmation immédiate.",
            "cashText": "Payez en espèces à la livraison. Le total reste calculé par le backend.",
            "cardOnDeliveryText": "Réservez maintenant et payez par carte à la livraison.",
            "complete": "Finaliser la réservation",
            "processing": "Traitement...",
            "summaryTitle": "Récapitulatif",
            "helmetIncluded": "Casque",
            "createdAccount": "Nous avons créé votre compte automatiquement pour gérer la réservation.",
            "existingEmailError": "Cet e-mail existe déjà. Veuillez d'abord vous connecter.",
            "pendingTitle": "Réservation créée",
            "pendingBody": "Votre {scooter} est réservé. Finalisez le paiement pour confirmer la réservation.",
            "paymentSucceeded": "Paiement effectué",
            "paymentPending": "Paiement en attente",
            "openPayment": "Ouvrir le paiement",
            "detailsRequired": "Veuillez d'abord renseigner les dates et la livraison.",
            "contactRequired": "Veuillez renseigner vos coordonnées.",
            "submitError": "La réservation a échoué. Veuillez réessayer.",
        },
        "account": {
            "guestTitle": "Votre compte",
            "guestBody": "Connectez-vous ou créez un compte pour gérer vos réservations, documents et profil.",
            "loginTab": "Connexion",
            "registerTab": "Créer un compte",
            "email": "E-mail",
            "password": "Mot de passe",
            "fullName": "Nom complet",
            "phone": "Téléphone",
            "signIn": "Connexion",
            "register": "Créer un compte",
            "bookings": "Mes réservations",
            "documents": "Documents",
            "notifications": "Notifications",
            "profile": "Profil",
            "newBooking": "+ Nouvelle réservation",
            "noBookings": "Aucune réservation pour le moment.",
            "noDocuments": "Aucun document téléchargé.",
            "noNotifications": "Aucune notification pour le moment.",
            "uploadDocument": "Téléverser un document",
            "saveProfile": "Enregistrer",
            "profileSaved": "Profil enregistré.",
            "logout": "Déconnexion",
            "documentType": "Type de document",
            "documentFile": "Fichier",
            "markRead": "Tout marquer comme lu",
            "country": "Pays",
            "language": "Langue",
            "currency": "Devise",
            "payNow": "Payer maintenant",
            "openPayment": "Ouvrir le paiement",
            "cancelBookingAction": "Annuler la réservation",
            "paymentStatus": "Statut du paiement",
            "paymentMethod": "Mode de paiement",
            "paymentPending": "Le paiement est toujours en attente.",
            "paymentStarted": "Le paiement a commencé. Continuez dans la fenêtre de paiement.",
            "paymentSucceeded": "Paiement effectué.",
            "paymentFailed": "Le paiement a échoué.",
            "bookingCancelled": "Réservation annulée.",
            "viewDocument": "Voir le document",
            "uploadedAt": "Téléversé",
            "documentUploaded": "Document téléversé.",
        },
    },
}


VEHICLE_COPY = {
    "honda-pcx-160": {
        "en": {
            "title": "Honda PCX 160",
            "description": "A premium Balinese city scooter with smooth power delivery, sharp efficiency, and relaxed comfort for longer island rides.",
            "rental_terms": "Helmet included. International driving permit recommended. Free cancellation up to 24 hours before delivery.",
        },
        "ru": {
            "title": "Honda PCX 160",
            "description": "Премиальный городской скутер для Бали: плавная тяга, отличная экономичность и комфорт для длительных поездок по острову.",
            "rental_terms": "Шлем включён. Международные права желательны. Бесплатная отмена за 24 часа до доставки.",
        },
    },
    "yamaha-nmax-155": {
        "en": {
            "title": "Yamaha NMAX 155",
            "description": "Comfort-focused maxi scooter with refined suspension, generous storage, and easy handling for everyday Bali travel.",
            "rental_terms": "Best for city and resort travel. Free cancellation up to 24 hours before delivery.",
        },
        "ru": {
            "title": "Yamaha NMAX 155",
            "description": "Комфортный макси-скутер с мягкой подвеской, вместительным багажником и лёгким управлением для поездок по Бали.",
            "rental_terms": "Отлично подходит для города и курортных районов. Бесплатная отмена за 24 часа.",
        },
    },
    "honda-adv-150": {
        "en": {
            "title": "Honda ADV 150",
            "description": "Adventure-inspired scooter with extra road confidence, upright ergonomics, and a capable stance for mixed Bali routes.",
            "rental_terms": "Ideal for riders exploring varied roads. Free cancellation up to 24 hours before delivery.",
        },
        "ru": {
            "title": "Honda ADV 150",
            "description": "Скутер с приключенческим характером, удобной посадкой и уверенным поведением на разных дорогах Бали.",
            "rental_terms": "Подходит для тех, кто планирует разные маршруты по острову. Бесплатная отмена за 24 часа.",
        },
    },
    "yamaha-aerox-155": {
        "en": {
            "title": "Yamaha Aerox 155",
            "description": "Sportier handling, quick throttle response, and a compact feel for riders who want a more energetic city scooter.",
            "rental_terms": "Designed for confident everyday riding. Free cancellation up to 24 hours before delivery.",
        },
        "ru": {
            "title": "Yamaha Aerox 155",
            "description": "Более спортивная управляемость и резвый отклик для тех, кто хочет динамичный городской скутер.",
            "rental_terms": "Хорош для уверенной повседневной езды. Бесплатная отмена за 24 часа.",
        },
    },
    "honda-vario-160": {
        "en": {
            "title": "Honda Vario 160",
            "description": "Practical, efficient, and easy to ride, making it a reliable choice for everyday errands and relaxed island cruising.",
            "rental_terms": "A balanced all-rounder for Bali. Free cancellation up to 24 hours before delivery.",
        },
        "ru": {
            "title": "Honda Vario 160",
            "description": "Практичный, экономичный и простой в управлении скутер для повседневных поездок по острову.",
            "rental_terms": "Сбалансированный вариант для Бали. Бесплатная отмена за 24 часа.",
        },
    },
    "royal-enfield-meteor": {
        "en": {
            "title": "Royal Enfield Meteor 350",
            "description": "Classic long-distance motorcycle with relaxed ergonomics, richer torque, and a distinctive touring feel.",
            "rental_terms": "Recommended for experienced riders. Free cancellation up to 24 hours before delivery.",
        },
        "ru": {
            "title": "Royal Enfield Meteor 350",
            "description": "Классический мотоцикл для дальних поездок с расслабленной посадкой, хорошей тягой и туристическим характером.",
            "rental_terms": "Рекомендуется опытным водителям. Бесплатная отмена за 24 часа.",
        },
    },
}


ADDON_COPY = {
    "helmet_full": {
        "en": {"name": "Full-Face Helmet", "description": "Premium full-face helmet with clean visor and comfortable fit."},
        "ru": {"name": "Закрытый шлем", "description": "Премиальный закрытый шлем с чистым визором и удобной посадкой."},
    },
    "insurance": {
        "en": {"name": "Full Insurance", "description": "Additional protection for a more relaxed trip."},
        "ru": {"name": "Полная страховка", "description": "Дополнительная защита для более спокойной поездки."},
    },
    "gps": {
        "en": {"name": "GPS Navigator", "description": "Navigation support for easy route planning around Bali."},
        "ru": {"name": "GPS-навигатор", "description": "Навигация для удобного построения маршрутов по Бали."},
    },
    "raincoat": {
        "en": {"name": "Rain Poncho", "description": "Lightweight rain layer for tropical showers."},
        "ru": {"name": "Дождевик", "description": "Лёгкая защита от тропического дождя."},
    },
    "phone_mount": {
        "en": {"name": "Phone Mount", "description": "Secure phone holder for maps and hands-free visibility."},
        "ru": {"name": "Держатель для телефона", "description": "Надёжное крепление для телефона и навигации."},
    },
    "wifi": {
        "en": {"name": "Pocket WiFi 4G", "description": "Portable connectivity for navigation and messaging."},
        "ru": {"name": "Карманный WiFi 4G", "description": "Мобильный интернет для навигации и связи."},
    },
    "helmet_open": {
        "en": {"name": "Open-Face Helmet", "description": "Lighter helmet option for shorter city rides."},
        "ru": {"name": "Открытый шлем", "description": "Более лёгкий вариант для коротких городских поездок."},
    },
    "bag": {
        "en": {"name": "Rear Bag", "description": "Compact luggage option for beach gear or essentials."},
        "ru": {"name": "Задняя сумка", "description": "Компактная сумка для пляжных вещей и повседневных мелочей."},
    },
}


ZONE_MINUTES = {
    "Seminyak": 30,
    "Canggu": 30,
    "Kuta": 25,
    "Legian": 30,
    "Denpasar": 35,
    "Jimbaran": 45,
    "Sanur": 45,
    "Ubud": 60,
    "Nusa Dua": 60,
    "Uluwatu": 90,
}


ACCENT_BY_SLUG = {
    "honda-pcx-160": "#0d1117",
    "yamaha-nmax-155": "#0a1628",
    "honda-adv-150": "#141414",
    "yamaha-aerox-155": "#0a0e1a",
    "honda-vario-160": "#1a1225",
    "royal-enfield-meteor": "#1a0c05",
}


def get_public_languages():
    return deepcopy(PUBLIC_LANGUAGES)


def get_public_site_content(lang):
    normalized = normalize_public_language(lang)
    return deep_merge(SITE_CONTENT_EN, SITE_CONTENT_OVERRIDES.get(normalized, {}))


def get_vehicle_copy(slug, lang):
    normalized = normalize_public_language(lang)
    copy_map = VEHICLE_COPY.get(slug, {})
    return copy_map.get(normalized) or copy_map.get("en") or {}


def get_addon_copy(code, lang):
    normalized = normalize_public_language(lang)
    copy_map = ADDON_COPY.get(code, {})
    return copy_map.get(normalized) or copy_map.get("en") or {}
