# Generated by Django 6.0.4 on 2026-04-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_refactor_marketing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"ordering": ["-priority", "-starts_at", "title"]},
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="promotioncampaign",
            options={"ordering": ["-starts_at", "name"]},
        ),
        migrations.RenameIndex(
            model_name="promocoderedemption",
            new_name="marketing_p_promo_c_063b97_idx",
            old_name="marketing_p_promo_c_21c974_idx",
        ),
        migrations.RenameIndex(
            model_name="promocoderedemption",
            new_name="marketing_p_user_id_02538b_idx",
            old_name="marketing_p_user_id_6547f5_idx",
        ),
        migrations.RenameIndex(
            model_name="promotioncampaign",
            new_name="marketing_p_code_245f15_idx",
            old_name="marketing_p_code_42e3ba_idx",
        ),
        migrations.AlterField(
            model_name="promocode",
            name="current_usage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_type",
            field=models.CharField(
                choices=[("PERCENT", "Percentage"), ("FIXED", "Fixed Amount")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
