# Generated by Django 5.2.13 on 2026-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_delete_referral'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='marketing_p_is_acti_68e171_idx'),
        ),
    ]
