# Generated by Codex on 2026-04-29

from django.db import migrations, models
import django.db.models.deletion


FAQ_SEED = [
    {
        'code': 'license_requirements',
        'sort_order': 10,
        'translations': {
            'en': {
                'question': 'Do I need an international driving license?',
                'answer': 'Yes. A valid motorcycle license or International Driving Permit is strongly recommended for riding legally in Bali.',
            },
            'ru': {
                'question': 'Нужны ли международные права?',
                'answer': 'Да. Для легальной езды по Бали очень желательно иметь права на мотоцикл или международное водительское удостоверение.',
            },
            'zh': {
                'question': '需要国际驾照吗？',
                'answer': '需要。为了在巴厘岛合法骑行，强烈建议您持有有效的摩托车驾照或国际驾驶许可。',
            },
            'id': {
                'question': 'Apakah saya memerlukan SIM internasional?',
                'answer': 'Ya. Untuk berkendara secara legal di Bali, sangat disarankan memiliki SIM motor yang valid atau International Driving Permit.',
            },
            'de': {
                'question': 'Brauche ich einen internationalen Führerschein?',
                'answer': 'Ja. Für das legale Fahren auf Bali empfehlen wir dringend einen gültigen Motorradführerschein oder einen internationalen Führerschein.',
            },
            'fr': {
                'question': "Ai-je besoin d'un permis de conduire international ?",
                'answer': "Oui. Pour rouler légalement à Bali, il est fortement recommandé d'avoir un permis moto valide ou un permis de conduire international.",
            },
        },
    },
    {
        'code': 'rental_price_included',
        'sort_order': 20,
        'translations': {
            'en': {
                'question': 'What is included in the rental price?',
                'answer': 'Base rental pricing comes from the backend. Helmets, delivery fees, and selected add-ons are clearly shown before confirmation.',
            },
            'ru': {
                'question': 'Что входит в стоимость аренды?',
                'answer': 'Базовая цена приходит с backend. Шлемы, доставка и выбранные допы видны до подтверждения брони.',
            },
            'zh': {
                'question': '租金里包含什么？',
                'answer': '基础租赁价格来自后端。头盔、配送费和所选附加服务都会在确认前清楚显示。',
            },
            'id': {
                'question': 'Apa saja yang termasuk dalam harga sewa?',
                'answer': 'Harga sewa dasar datang dari backend. Helm, biaya antar, dan add-on yang dipilih ditampilkan dengan jelas sebelum konfirmasi.',
            },
            'de': {
                'question': 'Was ist im Mietpreis enthalten?',
                'answer': 'Der Grundpreis kommt direkt aus dem Backend. Helme, Liefergebühren und ausgewählte Extras werden vor der Bestätigung klar angezeigt.',
            },
            'fr': {
                'question': 'Que comprend le prix de la location ?',
                'answer': 'Le tarif de base vient du backend. Les casques, les frais de livraison et les options choisies sont clairement affichés avant confirmation.',
            },
        },
    },
    {
        'code': 'delivery_process',
        'sort_order': 30,
        'translations': {
            'en': {
                'question': 'How does delivery work?',
                'answer': 'Choose your area, enter the address, and the checkout will use live delivery zones from the backend.',
            },
            'ru': {
                'question': 'Как работает доставка?',
                'answer': 'Выберите район, введите адрес, и checkout использует реальные зоны доставки с сервера.',
            },
            'zh': {
                'question': '配送是怎么安排的？',
                'answer': '选择您的区域并填写地址，结账流程会使用来自后端的实时配送区域数据。',
            },
            'id': {
                'question': 'Bagaimana cara kerja pengantaran?',
                'answer': 'Pilih area Anda, masukkan alamat, dan checkout akan memakai zona pengantaran live dari backend.',
            },
            'de': {
                'question': 'Wie funktioniert die Lieferung?',
                'answer': 'Wähle deinen Bereich, gib die Adresse ein, und der Checkout verwendet Live-Lieferzonen aus dem Backend.',
            },
            'fr': {
                'question': 'Comment fonctionne la livraison ?',
                'answer': "Choisissez votre zone, saisissez l'adresse et le checkout utilisera les zones de livraison en direct depuis le backend.",
            },
        },
    },
    {
        'code': 'manage_booking_later',
        'sort_order': 40,
        'translations': {
            'en': {
                'question': 'Can I manage my booking later?',
                'answer': 'Yes. Once you sign in or create an account during checkout, your bookings are visible in the account page.',
            },
            'ru': {
                'question': 'Можно ли потом управлять бронью?',
                'answer': 'Да. После входа или создания аккаунта во время оформления бронь появится в аккаунте.',
            },
            'zh': {
                'question': '之后还能管理我的订单吗？',
                'answer': '可以。只要您在结账时登录或创建账户，订单之后都会显示在账户页面中。',
            },
            'id': {
                'question': 'Apakah booking saya bisa dikelola nanti?',
                'answer': 'Bisa. Setelah masuk atau membuat akun saat checkout, booking Anda akan muncul di halaman akun.',
            },
            'de': {
                'question': 'Kann ich meine Buchung später verwalten?',
                'answer': 'Ja. Sobald du dich anmeldest oder beim Checkout ein Konto erstellst, erscheinen deine Buchungen im Konto-Bereich.',
            },
            'fr': {
                'question': 'Puis-je gérer ma réservation plus tard ?',
                'answer': 'Oui. Dès que vous vous connectez ou créez un compte pendant le checkout, vos réservations apparaissent dans la page de compte.',
            },
        },
    },
]


def seed_faq(apps, schema_editor):
    FAQItem = apps.get_model('support', 'FAQItem')
    FAQItemTranslation = apps.get_model('support', 'FAQItemTranslation')

    for item_data in FAQ_SEED:
        faq_item, _ = FAQItem.objects.update_or_create(
            code=item_data['code'],
            defaults={
                'is_active': True,
                'sort_order': item_data['sort_order'],
            },
        )
        for language, translation in item_data['translations'].items():
            FAQItemTranslation.objects.update_or_create(
                faq_item=faq_item,
                language=language,
                defaults={
                    'question': translation['question'],
                    'answer': translation['answer'],
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('faq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='support.faqitem')),
            ],
            options={
                'ordering': ['faq_item_id', 'language'],
                'unique_together': {('faq_item', 'language')},
            },
        ),
        migrations.RunPython(seed_faq, migrations.RunPython.noop),
    ]
