# Generated by Django 5.2.13 on 2026-04-28 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdocument',
            old_name='verified_at',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='userdocument',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userdocument',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('selfie', 'Selfie')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdocument',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='status',
            field=models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
