# Generated by Django 5.2.13 on 2026-04-29 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_userdocument_options_alter_userdocument_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['document', 'created_at'], name='documents_d_documen_d772a2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['status', 'created_at'], name='documents_d_status_c7f449_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['user', 'status', 'created_at'], name='documents_u_user_id_dc2fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['status', 'created_at'], name='documents_u_status_846731_idx'),
        ),
    ]
