# Generated by Django 5.2.13 on 2026-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookprocessinglog',
            name='payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webhookprocessinglog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookprocessinglog',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='webhookprocessinglog',
            index=models.Index(fields=['processed'], name='audit_webho_process_2e86c3_idx'),
        ),
    ]
