# Generated by Django 5.2.13 on 2026-04-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_webhookprocessinglog_payload_json_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhookprocessinglog',
            unique_together={('provider', 'event_id')},
        ),
    ]
