# Generated by Django 5.2.13 on 2026-04-29 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_webhookprocessinglog_unique_together'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminloginlog',
            index=models.Index(fields=['created_at'], name='audit_admin_created_6222b1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'created_at'], name='audit_audit_content_7b22cc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookprocessinglog',
            index=models.Index(fields=['created_at'], name='audit_webho_created_1ed592_idx'),
        ),
    ]
