# Generated by Django 5.2.13 on 2026-04-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='addon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
