# Generated by Django 5.2.13 on 2026-04-29 16:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0002_alter_addon_options_addon_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
