# Generated by Django 6.0.4 on 2026-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_stafftask_options_stafftask_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="avg_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="customerinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("call", "Call"),
                    ("email", "Email"),
                    ("chat", "Chat"),
                    ("booking", "Booking"),
                    ("payment", "Payment"),
                    ("support", "Support"),
                    ("review", "Review"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
