# Generated by Django 5.2.13 on 2026-04-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customerprofile_avg_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
