# Generated by Django 5.2.13 on 2026-04-28 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='catalog.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='catalog.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='vehicletranslation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='catalog.vehicletype'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='catalog_veh_status_50017e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['base_price_usd'], name='catalog_veh_base_pr_67ccc8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_featured'], name='catalog_veh_is_feat_6d7097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicletranslation',
            unique_together={('vehicle', 'language')},
        ),
    ]
