# Generated by Django 5.2.15 on 2026-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_vehicletranslation_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='base_price_usd',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
