# Generated by Django 5.2.15 on 2026-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_vehicle_base_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='base_price_idr',
            field=models.PositiveBigIntegerField(blank=True, help_text='Exact IDR amount entered by the admin. base_price_usd is derived from this and never used to recompute it, so the rupiah figure never drifts after saving.', null=True),
        ),
    ]
