# Generated by Django 5.2.13 on 2026-04-28 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryaddress'),
        ),
    ]
