# Generated by Django 5.2.13 on 2026-04-28 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityblock',
            name='source_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='bookings.booking'),
        ),
    ]
