# Generated by Django 6.0.4 on 2026-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_availabilityblock_source_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="pricing_snapshot_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
