# Generated by Django 5.2.13 on 2026-04-29 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_pricing_snapshot_json'),
        ('catalog', '0003_alter_vehicle_options'),
        ('delivery', '0005_alter_deliveryzone_center_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'created_at'], name='bookings_bo_user_id_5943d6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_at', 'end_at'], name='bookings_bo_start_a_7c429a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status', 'created_at'], name='bookings_bo_payment_6549cc_idx'),
        ),
    ]
