# Generated by Django 5.2.13 on 2026-04-28 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0006_alter_availabilityblock_source_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='BTC, ETH, USDT, etc.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(help_text='ERC20, TRC20, BEP20, etc.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('precision', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('external_event_id', models.CharField(help_text='For idempotency', max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'external_event_id'], name='crypto_paym_provide_2c4c9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CryptoInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_crypto', models.DecimalField(decimal_places=18, max_digits=36)),
                ('address', models.CharField(max_length=255)),
                ('payment_url', models.URLField(blank=True, max_length=500)),
                ('provider', models.CharField(max_length=50)),
                ('provider_invoice_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('expired', 'Expired'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_invoices', to='bookings.booking')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crypto_payments.cryptocurrency')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_invoice_id'], name='crypto_paym_provide_46a1c4_idx'), models.Index(fields=['status'], name='crypto_paym_status_389e7a_idx'), models.Index(fields=['address'], name='crypto_paym_address_cd5047_idx')],
            },
        ),
    ]
